/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uibeheer;

import DAL.Acteur;
import DAL.Film;
import DAL.Genre;
import Services.ActeurServices;
import Services.AutoCompletion;
import Services.FilmServices;
import Services.FrameServices;
import Services.GenreServices;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Ikke
 */
public class AddFilmFrame extends javax.swing.JFrame {
    /**
     * Creates new form AddFilmFrame
     */
    public AddFilmFrame() {
        initComponents();
        FillCbGenres();
        FillCbActeurs();
        AutoCompletion.enable(cbActeur1);
        AutoCompletion.enable(cbActeur2);
        AutoCompletion.enable(cbActeur3);
        AutoCompletion.enable(cbActeur4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbGenres = new javax.swing.JComboBox();
        cbActeur1 = new javax.swing.JComboBox();
        cbActeur2 = new javax.swing.JComboBox();
        cbActeur3 = new javax.swing.JComboBox();
        cbActeur4 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtJaar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInhoud = new javax.swing.JTextArea();
        btnSaveClose = new javax.swing.JButton();
        btnSaveNew = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Film Toevoegen");
        setBounds(new java.awt.Rectangle(700, 200, 0, 0));
        setResizable(false);

        jLabel1.setText("Titel:");

        jLabel2.setText("Genre:");

        jLabel3.setText("<html>Acteurs/<br>Actrices:<html>");

        cbActeur1.setEditable(true);
        cbActeur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActeur1ActionPerformed(evt);
            }
        });

        cbActeur2.setEnabled(false);
        cbActeur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActeur2ActionPerformed(evt);
            }
        });

        cbActeur3.setEnabled(false);
        cbActeur3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActeur3ActionPerformed(evt);
            }
        });

        cbActeur4.setEnabled(false);

        jLabel4.setText("Jaar:");

        jLabel5.setText("Inhoud:");

        txtInhoud.setColumns(20);
        txtInhoud.setLineWrap(true);
        txtInhoud.setRows(5);
        txtInhoud.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtInhoud);

        btnSaveClose.setText("<html>Save &<br>Close<html>");
        btnSaveClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCloseActionPerformed(evt);
            }
        });

        btnSaveNew.setText("<html>Save &<br> Add New<html>");
        btnSaveNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewActionPerformed(evt);
            }
        });

        btnClose.setText("Sluit");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveClose, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveNew, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbGenres, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbActeur3, javax.swing.GroupLayout.Alignment.LEADING, 0, 180, Short.MAX_VALUE)
                                    .addComponent(cbActeur1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbActeur2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbActeur4, 0, 180, Short.MAX_VALUE)))
                            .addComponent(txtJaar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbGenres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbActeur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbActeur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbActeur3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbActeur4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJaar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveNew, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCloseActionPerformed
        Save();
        FrameServices.GoToStart(this);
    }//GEN-LAST:event_btnSaveCloseActionPerformed

    private void btnSaveNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewActionPerformed
        Save();
        ClearAll();
    }//GEN-LAST:event_btnSaveNewActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        FrameServices.GoToStart(this);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cbActeur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActeur1ActionPerformed
       cbActeur2.setEnabled(true);
    }//GEN-LAST:event_cbActeur1ActionPerformed

    private void cbActeur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActeur2ActionPerformed
        cbActeur3.setEnabled(true);
    }//GEN-LAST:event_cbActeur2ActionPerformed

    private void cbActeur3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActeur3ActionPerformed
        cbActeur4.setEnabled(true);
    }//GEN-LAST:event_cbActeur3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFilmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFilmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFilmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFilmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFilmFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSaveClose;
    private javax.swing.JButton btnSaveNew;
    private javax.swing.JComboBox cbActeur1;
    private javax.swing.JComboBox cbActeur2;
    private javax.swing.JComboBox cbActeur3;
    private javax.swing.JComboBox cbActeur4;
    private javax.swing.JComboBox cbGenres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextArea txtInhoud;
    private javax.swing.JTextField txtJaar;
    private javax.swing.JTextField txtTitel;
    // End of variables declaration//GEN-END:variables

    private void Save() {
        String s = ""; //string voor acteurs
        String error = ""; //string voor de error
        
        Film f = new Film();
        if(!txtTitel.getText().isEmpty()){
           f.setTitel(txtTitel.getText()); 
        }
        else{
            error += "<html>Verplicht een titel in te vullen!<br><html>";
            lblError.setText(error);
        }
        if(cbGenres.getSelectedIndex()>0){
            f.setGenre(cbGenres.getSelectedItem().toString());
        }
        else{
            error += "<html>Verplicht een genre te selecteren!<br><html>";
            lblError.setText(error);
        }
        if(!txtJaar.getText().isEmpty()){
            f.setJaar(Integer.parseInt(txtJaar.getText()));
        }
        else{
            error += "<html>Verplicht een jaar in te vullen!<br><html>";
            lblError.setText(error);
        }
        if(!txtInhoud.getText().isEmpty()){
            f.setOmschrijving(txtInhoud.getText());
        }
        else{
            error += "<html>Verplicht een korte inhoud te geven!<br><html>";
            lblError.setText(error);
        }
        if(cbActeur1.getSelectedIndex()>0) s+= cbActeur1.getSelectedItem().toString();
        else{
            error += "<html>Verplicht tenmiste 1 acteur/actrice te selecteren!<html>";
            lblError.setText(error);
        }
        if(cbActeur2.getSelectedIndex()>0) s+= ", " + cbActeur2.getSelectedItem().toString();
        if(cbActeur3.getSelectedIndex()>0) s+= ", " + cbActeur3.getSelectedItem().toString();
        if(cbActeur4.getSelectedIndex()>0) s+= ", " + cbActeur4.getSelectedItem().toString();
        f.setActeurs(s);
        if(lblError.getText().isEmpty()){
           FilmServices.Save(f); 
        }
        else{
            return;
        }
    }

    private void ClearAll() {
        txtTitel.setText("");
        txtInhoud.setText("");
        txtJaar.setText("");
        cbGenres.setSelectedIndex(0);
        cbActeur1.setSelectedIndex(0);
        cbActeur2.setSelectedIndex(0);
        cbActeur3.setSelectedIndex(0);
        cbActeur4.setSelectedIndex(0);
        cbActeur2.setEnabled(false);
        cbActeur3.setEnabled(false);
        cbActeur4.setEnabled(false);
    }

    private void FillCbGenres() {
        List<Genre> list = GenreServices.GetAll();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("-- Select Genre --");
        for(Genre obj:list)
        {
            model.addElement(obj);
        }
        cbGenres.setModel(model);
    }

    private void FillCbActeurs() {
        List<Acteur> list = ActeurServices.GetAll();
        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        DefaultComboBoxModel model3 = new DefaultComboBoxModel();
        DefaultComboBoxModel model4 = new DefaultComboBoxModel();
        model1.addElement("-- Select Acteur/Actrice --");
        model2.addElement("-- Select Acteur/Actrice --");
        model3.addElement("-- Select Acteur/Actrice --");
        model4.addElement("-- Select Acteur/Actrice --");
        for(Acteur obj:list)
        {
            model1.addElement(obj);
            model2.addElement(obj);
            model3.addElement(obj);
            model4.addElement(obj);
        }
        cbActeur1.setModel(model1);
        cbActeur2.setModel(model2);
        cbActeur3.setModel(model3);
        cbActeur4.setModel(model4);
    }
    
}
