/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uibeheer;

import Services.FrameServices;
import java.awt.event.ActionEvent;
import javax.swing.JButton;

/**
 *
 * @author Ikke
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    private String s = "";
    public StartFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFilmToevoegen = new javax.swing.JButton();
        btnActeurToevoegen = new javax.swing.JButton();
        btnGenreToevoegen = new javax.swing.JButton();
        btnFilmVerwijderen = new javax.swing.JButton();
        btnSluiten = new javax.swing.JButton();
        btnGeleendeFilm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(700, 350, 0, 0));
        setResizable(false);

        btnFilmToevoegen.setText("Film Toevoegen");
        btnFilmToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmToevoegenActionPerformed(evt);
            }
        });

        btnActeurToevoegen.setText("Acteur/Actrice Toevoegen");
        btnActeurToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActeurToevoegenActionPerformed(evt);
            }
        });

        btnGenreToevoegen.setText("Genre Toevoegen");
        btnGenreToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreToevoegenActionPerformed(evt);
            }
        });

        btnFilmVerwijderen.setText("Film Verwijderen");
        btnFilmVerwijderen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmVerwijderenActionPerformed(evt);
            }
        });

        btnSluiten.setText("Sluiten");
        btnSluiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSluitenActionPerformed(evt);
            }
        });

        btnGeleendeFilm.setText("Geleende film toevoegen");
        btnGeleendeFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeleendeFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGeleendeFilm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFilmToevoegen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFilmVerwijderen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActeurToevoegen, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(btnGenreToevoegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnSluiten, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFilmToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenreToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActeurToevoegen, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnFilmVerwijderen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnGeleendeFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSluiten, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilmToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmToevoegenActionPerformed
        actionPerformed(evt);
        FrameServices.GoTo(s, this);
    }//GEN-LAST:event_btnFilmToevoegenActionPerformed

    private void btnFilmVerwijderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmVerwijderenActionPerformed
        actionPerformed(evt);
        FrameServices.GoTo(s, this);
    }//GEN-LAST:event_btnFilmVerwijderenActionPerformed

    private void btnGenreToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenreToevoegenActionPerformed
        actionPerformed(evt);
        FrameServices.GoTo(s, this);
    }//GEN-LAST:event_btnGenreToevoegenActionPerformed

    private void btnActeurToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActeurToevoegenActionPerformed
        actionPerformed(evt);
        FrameServices.GoTo(s, this);
    }//GEN-LAST:event_btnActeurToevoegenActionPerformed

    private void btnSluitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSluitenActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSluitenActionPerformed

    private void btnGeleendeFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeleendeFilmActionPerformed
        actionPerformed(evt);
        FrameServices.GoTo(s, this);
    }//GEN-LAST:event_btnGeleendeFilmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActeurToevoegen;
    private javax.swing.JButton btnFilmToevoegen;
    private javax.swing.JButton btnFilmVerwijderen;
    private javax.swing.JButton btnGeleendeFilm;
    private javax.swing.JButton btnGenreToevoegen;
    private javax.swing.JButton btnSluiten;
    // End of variables declaration//GEN-END:variables

    private void actionPerformed(ActionEvent evt) {
        s = "";
        s = ((JButton) evt.getSource()).getActionCommand();
    }
}
